areas = ['Phonology', 'Morphology', 'Nominal Categories', 'Nominal Syntax', 'Verbal Categories', 'Word Order', 'Simple Clauses', 'Complex Sentences', 'Lexicon', 'Sign Languages', 'Other']
features = [
  #[area id name values...]
  [0, '1A', 'Consonant Inventories',
    'Small', 'Moderately small', 'Average', 'Moderately large', 'Large'],
  [0, '2A', 'Vowel Quality Inventories',
    'Small vowel inventory (2-4)', 'Average vowel inventory (5-6)', 'Large vowel inventory (7-14)'],
  [0, '3A', 'Consonant-Vowel Ratio',
    'Low', 'Moderately low', 'Average', 'Moderately high', 'High'],
  [0, '4A', 'Voicing in Plosives and Fricatives',
    'No voicing contrast', 'Voicing contrast in plosives alone', 'Voicing contrast in fricatives alone', 'Voicing contrast in both plosives and fricatives'],
  [0, '5A', 'Voicing and Gaps in Plosive Systems',
    'Other', '/p t k b d g/', 'Missing /p/', 'Missing /g/', 'Both missing'],
  [0, '6A', 'Uvular Consonants',
    'No uvulars', 'Uvular stops only', 'Uvular continuants only', 'Uvular stops and continuants'],
  [0, '7A', 'Glottalized Consonants',
    'No glottalized consonants', 'Ejectives only', 'Implosives only', 'Glottalized resonants only', 'Ejectives and implosives', 'Ejectives and glottalized resonants', 'Implosives and glottalized resonants', 'Ejectives, implosives and glottalized resonants'],
  [0, '8A', 'Lateral Consonants',
    'No laterals', '/l/, no obstruent laterals', 'Laterals, but no /l/, no obstruent lateral', '/l/ and lateral obstruents', 'No /l/, but lateral obstruents'],
  [0, '9A', 'The Velar Nasal',
    'Velar nasal, also initially', 'Velar nasal, but not initially', 'No velar nasal'],
  [0, '10A', 'Vowel Nasalization',
    'Contrastive nasal vowels present', 'Contrastive nasal vowels absent'],
  [0, '10B', 'Nasal Vowels in West Africa',
    'no nasal vs. oral vowel contrast', 'two-way nasal vs. oral vowel contrast (/ṽ/ vs. /V/) without nasal spreading', 'two-way nasal vs. oral vowel contrast (/ṽ/ vs. /V/) with nasal spreading', 'four-way nasal vs. oral vowel contrast (/ṽ/ vs. /ṽː/ vs. /V/ vs. /Vː/) without nasal spreading', 'four-way nasal vs. oral vowel contrast (/ṽ/ vs. /ṽː/ vs. /V/ v /Vː/) with nasal spreading'],
  [0, '11A', 'Front Rounded Vowels',
    'None', 'High and mid', 'High only', 'Mid only'],
  [0, '12A', 'Syllable Structure',
    'Simple syllable structure', 'Moderately complex syllable structure', 'Complex syllable structure'],
  [0, '13A', 'Tone',
    'No tones', 'Simple tone system', 'Complex tone system'],
  [0, '14A', 'Fixed Stress Locations',
    'No fixed stress (mostly weight-sensitive stress)', 'Initial: stress is on the first syllable', 'Second: stress is on the second syllable', 'Third: stress is on the third syllable', 'Antepenultimate: stress is on the antepenultimate (third from the right) syllable', 'Penultimate: stress is on the penultimate (second from the right) syllable', 'Ultimate: stress is on the ultimate (last) syllable'],
  [0, '15A', 'Weight-Sensitive Stress',
    'Left-edge: Stress is on the first or second syllable', 'Left-oriented: The third syllable is involved', 'Right-edge: Stress on ultimate or penultimate syllable', 'Right-oriented: The antepenultimate is involved', 'Unbounded: Stress can be anywhere in the word', 'Combined: Both Right-edge and unbounded', 'Not predictable', 'Fixed stress (no weight-sensitivity)'],
  [0, '16A', 'Weight Factors in Weight-Sensitive Stress Systems',
    'No weight, or weight factor unknown', 'Long vowel: long vowels are heavy for stress', 'Coda consonant: closed syllables are heavy for stress', 'Long vowel + Coda: long vowels or closed syllables', 'Prominence: other factors are heavy for stress', 'Lexical: lexical stress, diacritic weight', 'Combined: two of the above factors determine weight'],
  [0, '17A', 'Rhythm Types',
    'Trochaic: left-hand syllable in the foot is strong', 'Iambic: right-hand syllable in the foot is strong', 'Dual: system has both trochaic and iambic feet', 'Undetermined: no clear foot type', 'Absent: no rhythmic stress'],
  [0, '18A', 'Absence of Common Consonants',
    'All present', 'No bilabials', 'No fricatives', 'No nasals', 'No bilabials or nasals', 'No fricatives or nasals'],
  [0, '19A', 'Presence of Uncommon Consonants',
    'None', 'Clicks', 'Labial-velars', 'Pharyngeals', "'Th' sounds", "Clicks, pharyngeals, and 'th'", "Pharyngeals and 'th'"],
  [1, '20A', 'Fusion of Selected Inflectional Formatives',
    'Exclusively concatenative', 'Exclusively isolating', 'Exclusively tonal', 'Tonal/isolating', 'Tonal/concatenative', 'Ablaut/concatenative', 'Isolating/concatenative'],
  [1, '21A', 'Exponence of Selected Inflectional Formatives',
    'Monoexponential case', 'Case + number', 'Case + referentiality', 'Case + TAM (tense-aspect-mood)', 'No case'],
  [1, '21B', 'Exponence of Tense-Aspect-Mood Inflection',
    'Monoexponential TAM', 'TAM+agreement', 'TAM+agreement+diathesis', 'TAM+agreement+construct', 'TAM+polarity', 'no TAM'],
  [1, '22A', 'Inflectional Synthesis of the Verb',
    '0-1 category per word', '2-3 categories per word', '4-5 categories per word', '6-7 categories per word', '8-9 categories per word', '10-11 categories per word', '12-13 categories per word'],
  [1, '23A', 'Locus of Marking in the Clause',
    'P is head-marked', 'P is dependent-marked', 'P is double-marked', 'P has no marking', 'Other types'],
  [1, '24A', 'Locus of Marking in Possessive Noun Phrases',
    'Possessor is head-marked', 'Possessor is dependent-marked', 'Possessor is double-marked', 'Possessor has no marking', 'Other types'],
  [1, '25A', 'Locus of Marking: Whole-language Typology',
    'Consistently head-marking', 'Consistently dependent-marking', 'Consistently double-marking', 'Consistently zero-marking', 'Inconsistent marking or other type'],
  [1, '25B', 'Zero Marking of A and P Arguments',
    'Zero-marking', 'Non-zero marking'],
  [1, '26A', 'Prefixing vs. Suffixing in Inflectional Morphology',
    'Little or no inflectional morphology', 'Predominantly suffixing', 'Moderate preference for suffixing', 'Approximately equal amounts of suffixing and prefixing', 'Moderate preference for prefixing', 'Predominantly prefixing'],
  [1, '27A', 'Reduplication',
    'Productive full and partial reduplication', 'Full reduplication only', 'No productive reduplication'],
  [1, '28A', 'Case Syncretism',
    'Inflectional case marking is absent or minimal', 'Inflectional case marking is syncretic for core cases only', 'Inflectional case marking is syncretic for core and non-core cases', 'Inflectional case marking is never syncretic'],
  [1, '29A', 'Syncretism in Verbal Person/Number Marking',
    'No subject person/number marking', 'Subject person/number marking is syncretic', 'Subject person/number marking is never syncretic'],
  [2, '30A', 'Number of Genders',
    'None', 'Two', 'Three', 'Four', 'Five or more'],
  [2, '31A', 'Sex-based and Non-sex-based Gender Systems',
    'No gender system', 'Sex-based gender system', 'Non-sex-based gender system'],
  [2, '32A', 'Systems of Gender Assignment',
    'No gender system', 'Semantic assignment', 'Semantic and formal assignment'],
  [2, '33A', 'Coding of Nominal Plurality',
    'Plural prefix', 'Plural suffix', 'Plural stem change', 'Plural tone', 'Plural by complete reduplication of stem', 'Morphological plural with no method primary', 'Plural word', 'Plural clitic', 'No plural'],
  [2, '34A', 'Occurrence of Nominal Plurality',
    'No nominal plural', 'Plural only in human nouns, optional', 'Plural only in human nouns, obligatory', 'Plural in all nouns, always optional', 'Plural in all nouns, optional in inanimates', 'Plural in all nouns, always obligatory'],
  [2, '35A', 'Plurality in Independent Personal Pronouns',
    'No independent subject pronouns', 'Number-indifferent pronouns', 'Person-number affixes', 'Person-number stem', 'Person-number stem with a pronominal plural affix', 'Person-number stem with a nominal plural affix', 'Person stem with a pronominal plural affix', 'Person stem with a nominal plural affix'],
  [2, '36A', 'The Associative Plural',
    'Associative plural marker also used for additive plurals', 'Special bound associative plural marker', 'Special non-bound associative plural marker', 'Associative plural absent'],
  [2, '37A', 'Definite Articles',
    'Definite word distinct from demonstrative', 'Demonstrative word used as marker of definiteness', 'Definite affix on noun', 'No definite article but indefinite article', 'Neither definite nor indefinite article'],
  [2, '38A', 'Indefinite Articles',
    "Indefinite word distinct from numeral for 'one'", "Numeral for 'one' is used as indefinite article", 'Indefinite affix on noun', 'No indefinite article but definite article', 'Neither indefinite nor definite'],
  [2, '39A', 'Inclusive/Exclusive Distinction in Independent Pronouns',
    'No grammaticalised marking at all', "'We' and 'I' identical", 'No inclusive/exclusive opposition', 'Only inclusive differentiated', 'Inclusive and exclusive differentiated'],
  [2, '39B', 'Inclusive/Exclusive Forms in Pama-Nyungan',
    'No inclusive/exclusive opposition', 'Inclusive and exclusive differentiated'],
  [2, '40A', 'Inclusive/Exclusive Distinction in Verbal Inflection',
    'No person marking at all', "'We' and 'I' identical", 'No inclusive/exclusive opposition', 'Only inclusive differentiated', 'Inclusive and exclusive differentiated'],
  [2, '41A', 'Distance Contrasts in Demonstratives',
    'No distance contrast', 'Two-way contrast', 'Three-way contrast', 'Four-way contrast', 'Five (or more)-way contrast'],
  [2, '42A', 'Pronominal and Adnominal Demonstratives',
    'Same forms', 'Different stems', 'Different inflectional features'],
  [2, '43A', 'Third Person Pronouns and Demonstratives',
    'Third person pronouns and demonstratives are unrelated to demonstratives', 'Third person pronouns and demonstratives are related to all demonstratives', 'Third person pronouns and demonstratives are related to remote demonstratives', 'Third person pronouns and demonstratives are related to non-remote demonstratives', 'Third person pronouns and demonstratives are related by gender markers', 'Third person pronouns and demonstratives are related for non-human reference'],
  [2, '44A', 'Gender Distinctions in Independent Personal Pronouns',
    'Gender distinctions in 3rd person plus 1st and/or 2nd person', 'Gender distinctions in 3rd person only, but in both singular and non-singular', 'Gender distinctions in 3rd person singular only', 'Gender distinctions in 1st or 2nd person but not 3rd', 'Gender distinctions in 3rd person non-singular only', 'No gender distinctions'],
  [2, '45A', 'Politeness Distinctions in Pronouns',
    'Second person pronouns encode no politeness distinction', 'Second person pronouns encode a binary politeness distinction', 'Second person pronouns encode multiple politeness distinctions', 'Second person pronouns are dominantly avoided for politeness reasons'],
  [2, '46A', 'Indefinite Pronouns',
    'Interrogative-based indefinites', 'Generic-noun-based indefinites', 'Special indefinites', 'Mixed indefinites', 'Existential construction'],
  [2, '47A', 'Intensifiers and Reflexive Pronouns',
    'Intensifiers and reflexive pronouns are formally identical', 'Intensifiers and reflexive pronouns are formally differentiated'],
  [2, '48A', 'Person Marking on Adpositions',
    'No adpositions', 'Adpositions without person marking', 'Person marking for pronouns only', 'Person marking for pronouns and nouns'],
  [2, '49A', 'Number of Cases',
    'No morphological case-marking', '2 case categories', '3 case categories', '4 case categories', '5 case categories', '6-7 case categories', '8-9 case categories', '10 or more case categories', 'Exclusively borderline morphological case-marking'],
  [2, '50A', 'Asymmetrical Case-Marking',
    'No morphological case-marking', 'Symmetrical case-marking', 'Additive-quantitatively asymmetrical case-marking', 'Subtractive-quantitatively asymmetrical case-marking', 'Qualitatively asymmetrical case-marking', 'Syncretism in relevant NP-types'],
  [2, '51A', 'Position of Case Affixes',
    'Case suffixes', 'Case prefixes', 'Case coded by tone', 'Case coded by changes within noun stem', 'Mixed morphological case strategies with none primary', 'Postpositional clitics', 'Prepositional clitics', 'Inpositional clitics', 'Neither case affixes nor adpositional clitics'],
  [2, '52A', 'Comitatives and Instrumentals',
    'Identity', 'Differentiation', 'Mixed'],
  [2, '53A', 'Ordinal Numerals',
    'Zero: Ordinal numerals do not exist', 'One: No distinction of cardinal and ordinal numerals', "First: Cardinal and ordinal numerals are identical except for 'one' and 'first'", 'One-th: One-th: Ordinal numerals are derived from cardinal numerals', "First/One-th: All ordinal numerals are derived from cardinal numerals with different allomorphs for 'first' one of which is morphologically independent of 'one'", "Two-th: Two-th: Ordinal numerals from 'two' upwards are derived from cardinal numerals, 'first' is suppletive", "Second: 'First' and a small set of consecutive higher ordinal numerals are suppletive", 'Variou-th: Other solutions'],
  [2, '54A', 'Distributive Numerals',
    'No distributive numerals', 'Marked by reduplication', 'Marked by prefix', 'Marked by suffix', 'Marked by preceding word', 'Marked by following word', 'Marked by mixed or other strategies'],
  [2, '55A', 'Numeral Classifiers',
    'Numeral classifiers are absent', 'Numeral classifiers are optional', 'Numeral classifiers are obligatory'],
  [2, '56A', 'Conjunctions and Universal Quantifiers',
    'Formally different', 'Formally similar, not involving interrogative expression', 'Formally similar, involving interrogative expression'],
  [2, '57A', 'Position of Pronominal Possessive Affixes',
    'Possessive prefixes', 'Possessive suffixes', 'Both possessive prefixes and possessive suffixes, with neither primary', 'No possessive affixes'],
  [3, '58A', 'Obligatory Possessive Inflection',
    'Obligatorily possessed nouns exist', 'No obligatorily possessed nouns'],
  [3, '58B', 'Number of Possessive Nouns',
    'None reported', 'One', 'Two to four', 'Five or more'],
  [3, '59A', 'Possessive Classification',
    'No possessive classification', 'Two classes', 'Three to five classes', 'More than five classes'],
  [3, '60A', 'Genitives, Adjectives and Relative Clauses',
    'Weakly differentiated', 'Moderately differentiated, with genitives and adjectives collapsed', 'Moderately differentiated, with genitives and relative clauses collapsed', 'Moderately differentiated, with adjectives and relative clauses collapsed', 'Moderately differentiated; other', 'Highly differentiated'],
  [3, '61A', 'Adjectives without Nouns',
    'Adjective may not occur without noun', 'Adjective may occur without noun, and without marking', 'Adjective may occur without noun, obligatorily marked by prefix', 'Adjective may occur without noun, obligatorily marked by suffix', 'Adjective may occur without noun, obligatorily marked by preceding word', 'Adjective may occur without noun, obligatorily marked by following word', 'Adjective may occur without noun, obligatorily marked by mixed or other strategies'],
  [3, '62A', 'Action Nominal Constructions',
    'Sentential: dependent-marking of the finite clause is retained for S, A and P', 'Possessive-Accusative: S/A treated as possessors, P retains sentential marking', 'Ergative-Possessive: S/P treated as possessors, A treated differently', 'Double-Possessive: All major arguments treated as possessors', 'Other: Minor patterns', 'Mixed: Several patterns in the same language', 'Not both A and P in the same construction', 'No action nominals'],
  [3, '63A', 'Noun Phrase Conjunction',
    "AND-languages: 'and' and 'with' are not identical", "WITH-languages: 'and' and 'with' are identical"],
  [3, '64A', 'Nominal and Verbal Conjunction',
    'Nominal and verbal conjunction are largely identical', 'Nominal and verbal conjunction are different', 'Nominal and verbal conjunction are primarily expressed by juxtaposition'],
  [4, '65A', 'Perfective/Imperfective Aspect',
    'Grammatical marking of perfective/imperfective distinction', 'No grammatical marking of perfective/imperfective distinction'],
  [4, '66A', 'The Past Tense',
    'Past/non-past distinction marked; no remoteness distinction', 'Past/non-past distinction marked; 2-3 degrees of remoteness distinguished', 'Past/non-past distinction marked; at least 4 degrees of remoteness distinguished', 'No grammatical marking of past/non-past distinction'],
  [4, '67A', 'The Future Tense',
    'Inflectional marking of future/non-future distinction', 'No inflectional marking of future/non-future distinction'],
  [4, '68A', 'The Perfect',
    "Perfect of the 'have'-type (derived from a possessive construction)", "Perfect derived from word meaning 'finish' or 'already'", 'Other perfect', 'No perfect'],
  [4, '69A', 'Position of Tense-Aspect Affixes',
    'Tense-aspect prefixes', 'Tense-aspect suffixes', 'Tense-aspect tone', 'Combination of tense-aspect strategies with none primary', 'No tense-aspect inflection'],
  [4, '70A', 'The Morphological Imperative',
    'The language has morphologically dedicated second singular as well as second plural imperatives', 'The language has morphologically dedicated second singular imperatives but no morphologically dedicated second plural imperatives', 'The language has morphologically dedicated second plural imperatives but no morphologically dedicated second singular imperatives', 'The language has morphologically dedicated second person imperatives that do not distinguish between singular and plural', 'The language has no morphologically dedicated second-person imperatives at all'],
  [4, '71A', 'The Prohibitive',
    'The prohibitive uses the verbal construction of the second singular imperative and a sentential negative strategy found in (indicative) declaratives', 'The prohbitive uses the verbal construction of the second singular imperative and a sentential negative strategy not found in (indicative) declaratives', 'The prohibitive uses a verbal construction other than the second singular imperative and a sentential negative strategy found in (indicative) declaratives', 'The prohibitive uses a verbal construction other than the second singular imperative and a sentential negative strategy not found in (indicative) declaratives'],
  [4, '72A', 'Imperative-Hortative Systems',
    'The language has a maximal system, but not a minimal one', 'The language has a minimal system, but not a maximal one', 'The language has both a maximal and a minimal system', 'The language has neither a maximal nor a minimal system'],
  [4, '73A', 'The Optative',
    'Inflectional optative present', 'Inflectional optative absent'],
  [4, '74A', 'Situational Possibility',
    'The language can express situational possibility with affixes on verbs', 'The language cannot express situational possibility with affixes on verbs, but with verbal constructions', 'The language cannot express situational possibility with affixes on verbs or with verbal constructions, but with other kinds of markers'],
  [4, '75A', 'Epistemic Possibility',
    'The language can express epistemic possibility with verbal constructions', 'The language cannot express epistemic possibility with verbal constructions, but with affixes on verbs', 'The language cannot express epistemic possibility with verbal constructions or with affixes on verbs, but with other kinds of markers'],
  [4, '76A', 'Overlap between Situational and Epistemic Modal Marking',
    'The language has markers that can code both situational and epistemic modality, both for possibility and necessity', 'The language has markers that can code both situational and epistemic modality, but only for possibility or for necessity', 'The language has no markers that can code both situational and epistemic modality'],
  [4, '77A', 'Semantic Distinctions of Evidentiality',
    'No grammatical evidentials', 'Only indirect evidentials', 'Both direct and indirect evidentials'],
  [4, '78A', 'Coding of Evidentiality',
    'No grammatical evidentials', 'Verbal affix or clitic', 'Part of the tense system', 'Separate particle', 'Modal morpheme', 'Mixed systems'],
  [4, '79A', 'Suppletion According to Tense and Aspect',
    'Suppletion according to tense', 'Suppletion according to aspect', 'Suppletion in both tense and aspect', 'No suppletion in tense or aspect'],
  [4, '79B', 'Suppletion in Imperatives and Hortatives',
    'A regular and a suppletive form alternate', 'Imperative', 'Hortative', 'Imperative and Hortative', 'None (= no suppletive imperatives reported in the reference material)'],
  [4, '80A', 'Verbal Number and Suppletion',
    'No singular-(dual)-plural pairs/triples', 'Singular-plural pairs, no suppletion', 'Singular-plural pairs, suppletion', 'Singular-dual-plural triples, no suppletion', 'Singular-dual-plural triples, suppletion'],
  [5, '81A', 'Order of Subject, Object and Verb',
    'Subject-object-verb (SOV)', 'Subject-verb-object (SVO)', 'Verb-subject-object (VSO)', 'Verb-object-subject (VOS)', 'Object-verb-subject (OVS)', 'Object-subject-verb (OSV)', 'Lacking a dominant word order'],
  [5, '81B', 'Languages with two Dominant Orders of Subject, Object, and Verb',
    'SOV or SVO', 'VSO or VOS', 'SVO or VSO', 'SVO or VOS', 'SOV or OVS'],
  [5, '82A', 'Order of Subject and Verb',
    'Subject precedes verb (SV)', 'Subject follows verb (VS)', 'Both orders with neither order dominant'],
  [5, '83A', 'Order of Object and Verb',
    'Object precedes verb (OV)', 'Object follows verb (VO)', 'Both orders with neither order dominant'],
  [5, '84A', 'Order of Object, Oblique, and Verb',
    'Verb-object-oblique (VOX)', 'Oblique-verb-object (XVO)', 'Oblique-object-verb (XOV)', 'Object-oblique-verb (OXV)', 'Object-verb-oblique (OVX)', 'More than one order with none dominant'],
  [5, '85A', 'Order of Adposition and Noun Phrase',
    'Postpositions', 'Prepositions', 'Inpositions', 'More than one adposition type with none dominant', 'No adpositions'],
  [5, '86A', 'Order of Genitive and Noun',
    'Genitive-noun (GenN)', 'Noun-genitive (NGen)', 'Both orders occur with neither order dominant'],
  [5, '87A', 'Order of Adjective and Noun',
    'Modifying adjective precedes noun (AdjN)', 'Modifying adjective follows noun (NAdj)', 'Both orders of noun and modifying adjective occur, with neither dominant', 'Adjectives do not modify nouns, occurring as predicates in internally headed relative clauses'],
  [5, '88A', 'Order of Demonstrative and Noun',
    'Demonstrative word precedes noun (DemN)', 'Demonstrative word follows noun (NDem)', 'Demonstrative prefix on noun', 'Demonstrative suffix on noun', 'Demonstrative simultaneously before and after noun', 'Two or more of above types with none dominant'],
  [5, '89A', 'Order of Numeral and Noun',
    'Numeral precedes noun (NumN)', 'Numeral follows noun (NNum)', 'Both orders of numeral and noun with neither order dominant', 'Numeral only modifies verb'],
  [5, '90A', 'Order of Relative Clause and Noun',
    'Relative clause follows noun (NRel)', 'Relative clause precedes noun (RelN)', 'Internally-headed relative clause', 'Correlative relative clause', 'Adjoined relative clause', 'Double-headed relative clause', 'Mixed types of relative clause with none dominant'],
  [5, '90B', 'Prenominal relative clauses',
    'Relative clause-Noun (RelN) dominant', 'RelN or NRel', 'RelN or internally-headed', 'RelN or correlative', 'RelN or double-headed'],
  [5, '90C', 'Postnominal relative clauses',
    'Noun-Relative clause (NRel) dominant', 'NRel or RelN', 'NRel or internally-headed', 'NRel or correlative'],
  [5, '90D', 'Internally-headed relative clauses',
    'Internally-headed relative clause dominant', 'Internally-headed or RelN', 'Internally-headed or NRel', 'Internally-headed or correlative', 'Internally-headed or double-headed', 'Internally-headed occurs as nondominant type', 'Internally-headed exists'],
  [5, '90E', 'Correlative relative clauses',
    'Correlative relative clause dominant', 'Correlative or RelN', 'Correlative or NRel', 'Correlative or internally-headed', 'Correlative or adjoined', 'Correlative as nondominant type', 'Correlative exists'],
  [5, '90F', 'Adjoined relative clauses',
    'Adjoined relative clause dominant', 'Adjoined or correlative'],
  [5, '90G', 'Double-headed relative clauses',
    'Double-headed dominant', 'Double-headed or RelN', 'Double-headed or internally-headed', 'Double-headed as nondominant type'],
  [5, '91A', 'Order of Degree Word and Adjective',
    'Degree word precedes adjective (DegAdj)', 'Degree word follows adjective (AdjDeg)', 'Both orders occur with neither order dominant'],
  [5, '92A', 'Position of Polar Question Particles',
    'Question particle at beginning of sentence', 'Question particle at end of sentence', 'Question particle in second position in sentence', 'Question particle with other position', 'Question particle in either of two positions', 'No question particle'],
  [5, '93A', 'Position of Interrogative Phrases in Content Questions',
    'Interrogative phrases obligatorily initial', 'Interrogative phrases not obligatorily initial', 'Mixed, some interrogative phrases obligatorily initial, some not'],
  [5, '94A', 'Order of Adverbial Subordinator and Clause',
    'Adverbial subordinators which are separate words and which appear at the beginning of the subordinate clause', 'Adverbial subordinators which are separate words and which appear at the end of the subordinate clause', 'Clause-internal adverbial subordinators', 'Suffixal adverbial subordinators', 'More than one type of adverbial subordinators with none dominant'],
  [5, '95A', 'Relationship between the Order of Object and Verb and the Order of Adposition and Noun Phrase',
    'Object-verb and postpositional (OV&Postp)', 'Object-verb and prepositional (OV&Prep)', 'Verb-object and postpositional (VO&Postp)', 'Verb-object and prepositional (VO&Prep)', 'Languages not falling into one of the preceding four types'],
  [5, '96A', 'Relationship between the Order of Object and Verb and the Order of Relative Clause and Noun',
    'Object-verb and relative clause-noun (OV&RelN)', 'Object-verb and noun-relative clause (OV&NRel)', 'Verb-object and relative clause-noun (VO&RelN)', 'Verb-object and noun-relative clause (VO&NRel)', 'Languages not falling into one of the preceding four types'],
  [5, '97A', 'Relationship between the Order of Object and Verb and the Order of Adjective and Noun',
    'Object-verb and adjective-noun (OV&AdjN)', 'Object-verb and noun-adjective (OV&NAdj)', 'Verb-object and adjective-noun (VO&AdjN)', 'Verb-object and noun-adjective (VO&NAdj)', 'Languages not falling into one of the preceding four types'],
  [6, '98A', 'Alignment of Case Marking of Full Noun Phrases',
    'Neutral', 'Nominative - accusative (standard)', 'Nominative - accusative (marked nominative)', 'Ergative - absolutive', 'Tripartite', 'Active - inactive'],
  [6, '99A', 'Alignment of Case Marking of Pronouns',
    'Neutral', 'Nominative - accusative (standard)', 'Nominative - accusative (marked nominative)', 'Ergative - absolutive', 'Tripartite', 'Active - inactive', 'None'],
  [6, '100A', 'Alignment of Verbal Person Marking',
    'Neutral alignment (no verbal person marking)', 'Accusative alignment', 'Ergative alignment', 'Active alignment', 'Hierarchical alignment', 'Split alignment'],
  [6, '101A', 'Expression of Pronominal Subjects',
    'Pronominal subjects are expressed by pronouns in subject position that are normally if not obligatorily present', 'Pronominal subjects are expressed by affixes on verbs', 'Pronominal subjects are expressed by clitics with variable host', 'Pronominal subjects are expressed by subject pronouns that occur in a different syntactic position from full noun phrase subjects', 'Pronominal subjects are expressed only by pronouns in subject position, but these pronouns are often left out', 'More than one of the above types with none dominant'],
  [6, '102A', 'Verbal Person Marking',
    'No person marking of any argument', 'Person marking of only the A argument', 'Person marking of only the P argument', 'Person marking of the A or P argument', 'Person marking of both the A and P arguments'],
  [6, '103A', 'Third Person Zero of Verbal Person Marking',
    'No person marking of the S', 'No zero realization of third person S forms', 'Zero realization of some third person singular forms', 'Zero realization of all third person singular S forms', 'Zero realization of all third person forms/No third person S forms', 'Zero realization only of third person non-singular'],
  [6, '104A', 'Order of Person Markers on the Verb',
    'A and P do not or do not both occur on the verb', 'A precedes P', 'P precedes A', 'Both orders of A and P occur', 'A and P are fused'],
  [6, '105A', "Ditransitive Constructions: The Verb 'Give'",
    'Indirect-object construction', 'Double-object construction', 'Secondary-object construction', 'Mixed'],
  [6, '106A', 'Reciprocal Constructions',
    'There are no non-iconic reciprocal constructions.', 'All reciprocal constructions are formally distinct from reflexive constructions.', 'There are both reflexive and non-reflexive reciprocal constructions.', 'The reciprocal and reflexive constructions are formally identical.'],
  [6, '107A', 'Passive Constructions',
    'There is a passive construction', 'There is no passive construction'],
  [6, '108A', 'Antipassive Constructions',
    'Antipassive with patient-like argument left implicit', 'Antipassive with patient-like argument expressed as oblique complement', 'No antipassive'],
  [6, '108B', 'Productivity of the Antipassive Construction',
    'productive', 'partially productive', 'not productive', 'no antipassive'],
  [6, '109A', 'Applicative Constructions',
    'Benefactive object only; both bases', 'Benefactive object only; transitive base only', 'Benefactive and other; both bases', 'Benefactive and other; transitive base only', 'Non-benefactive object only; both bases', 'Non-benefactive object only; transitive base only', 'Non-benefactive object only; intransitive base only', 'No applicative construction'],
  [6, '109B', 'Other Roles of Applied Objects',
    'Instrument', 'Locative', 'Instrument and locative', 'No other roles (= Only benefactive)', 'No applicative construction'],
  [6, '110A', 'Periphrastic Causative Constructions',
    'Sequential type but no purposive type', 'Purposive type but no sequential type', 'Both sequential type and purposive type'],
  [6, '111A', 'Nonperiphrastic Causative Constructions',
    'No morphological type or compound type', 'Morphological type but no compound type', 'Compound type but no morphological type', 'Both morphological type and compound type'],
  [6, '112A', 'Negative Morphemes',
    'Negative affix', 'Negative particle', 'Negative auxiliary verb', 'Negative word, unclear if verb or particle', 'Variation between negative word and affix', 'Double negation'],
  [6, '113A', 'Symmetric and Asymmetric Standard Negation',
    'Symmetric standard negation only: Type Sym', 'Asymmetric standard negation only: Type Asy', 'Symmetric and asymmetric standard negation: Type SymAsy'],
  [6, '114A', 'Subtypes of Asymmetric Standard Negation',
    'In finiteness: Subtype A/Fin', 'In reality status: Subtype A/NonReal', 'In other grammatical categories: Subtype A/Cat', 'In finiteness and reality status: Subtypes A/Fin and A/NonReal', 'In finiteness and other grammatical categories: Subtypes A/Fin and A/Cat', 'In reality status and other grammatical categories: Subtypes A/NonReal and A/Cat', 'Non-assignable (no asymmetry found)'],
  [6, '115A', 'Negative Indefinite Pronouns and Predicate Negation',
    'Negative indefinites co-occur with predicate negation', 'Negative indefinites preclude predicate negation', 'Negative indefinites show mixed behaviour', 'Negative existential construction'],
  [6, '116A', 'Polar Questions',
    'Question particle', 'Interrogative verb morphology', 'Question particle and interrogative verb morphology', 'Interrogative word order', 'Absence of declarative morphemes', 'Interrogative intonation only', 'No interrogative-declarative distinction'],
  [6, '117A', 'Predicative Possession',
    'Locational Possessive', 'Genitive Possessive', 'Topic Possessive', 'Conjunctional Possessive', 'Have-Possessive'],
  [6, '118A', 'Predicative Adjectives',
    'Predicative adjectives have verbal encoding', 'Predicative adjectives have nonverbal encoding', 'Predicative adjectives have mixed encoding'],
  [6, '119A', 'Nominal and Locational Predication',
    'Split (i.e. different) encoding of nominal and locational predication', 'Shared (i.e. identical) encoding of nominal and locational predication'],
  [6, '120A', 'Zero Copula for Predicate Nominals',
    'Zero copula is impossible', 'Zero copula is possible'],
  [6, '121A', 'Comparative Constructions',
    'Locational Comparative', 'Exceed Comparative', 'Conjoined Comparative', 'Particle Comparative'],
  [7, '122A', 'Relativization on Subjects',
    'Relative pronoun', 'Non-reduction', 'Pronoun-retention', 'Gap'],
  [7, '123A', 'Relativization on Obliques',
    'Relative Pronoun Strategy', 'Non-Reduction Strategy', 'Pronoun-Retention Strategy', 'Gap Strategy', 'Not possible'],
  [7, '124A', "'Want' Complement Subjects",
    'The complement subject is left implicit', 'The complement subject is expressed overtly', 'Both construction types exist', "'Want' is expressed as a desiderative verbal affix", "'Want' is expressed as an uninflected desiderative particle"],
  [7, '125A', 'Purpose Clauses',
    'Balanced', 'Balanced/deranked', 'Deranked'],
  [7, '126A', "'When' Clauses",
    'Balanced', 'Balanced/deranked', 'Deranked'],
  [7, '127A', 'Reason Clauses',
    'Balanced', 'Balanced/deranked', 'Deranked'],
  [7, '128A', 'Utterance Complement Clauses',
    'Balanced', 'Balanced/deranked', 'Deranked'],
  [8, '129A', 'Hand and Arm',
    "Identity: a single word denotes both 'hand' and 'arm'", "Differentiation: one word denotes 'hand' and another, different word denotes 'arm'"],
  [8, '130A', 'Finger and Hand',
    "Identity: a single word denotes both 'hand' and 'finger' and/or 'fingers'", "Differentiation: one word denotes 'hand' and another, different word denotes 'finger' (or, very rarely, 'fingers')"],
  [8, '130B', "Cultural Categories of Languages with Identity of 'Finger' and 'Hand'",
    'Hunter-gatherers', 'Farmer-foragers', 'Full-fledged farmers'],
  [8, '131A', 'Numeral Bases',
    'Decimal', 'Hybrid vigesimal-decimal', 'Pure vigesimal', 'Other base', 'Extended body-part system', 'Restricted'],
  [8, '132A', 'Number of Non-Derived Basic Colour Categories',
    '3 categories', 'Between 3 and 4 categories', '4 categories', 'Between 4 and 5 categories', '5 categories', 'Between 5 and 6 categories', '6 categories'],
  [8, '133A', 'Number of Basic Colour Categories',
    '3, between 3 and 4, or 4 categories', 'Between 4 and 5, 5, or between 5 and 6 categories', '6 or between 6 and 7 categories', '7 or between 7 and 8 categories', '8 or between 8 and 9 categories', '9, between 9 and 10, or 10 categories', 'More than 10 categories'],
  [8, '134A', 'Green and Blue',
    'Green and blue', "Green-or-blue ('grue')", 'Black-or-green-or-blue', 'Black-or-blue and green', 'Yellow-or-green-or-blue', 'Yellow-or-green and blue', 'Green and blue not both encoded in any basic color term'],
  [8, '135A', 'Red and Yellow',
    'Red and yellow', 'Red-or-yellow', 'Red and yellow-or-green-or-blue', 'Red and yellow-or-green', 'Red and yellow not both encoded in any basic color term'],
  [8, '136A', 'M-T Pronouns',
    'No M-T pronouns', 'M-T pronouns, paradigmatic', 'M-T pronouns, non-paradigmatic'],
  [8, '136B', 'M in First Person Singular',
    'No m in first person singular', 'm in first person singular'],
  [8, '137A', 'N-M Pronouns',
    'No N-M pronouns', 'N-M pronouns, paradigmatic', 'N-M pronouns, non-paradigmatic'],
  [8, '137B', 'M in Second Person Singular',
    'No m in second person singular', 'm in second person singular'],
  [8, '138A', 'Tea',
    'Words derived from Sinitic cha', 'Words derived from Min Nan Chinese te', 'Others'],
  [9, '139A', 'Irregular Negatives in Sign Languages',
    'No irregular negatives', 'One irregular negative', 'Some irregular negatives (2-5)', 'Many irregular negatives (more than 5)'],
  [9, '140A', 'Question Particles in Sign Languages',
    'No question particle', 'One question particle', 'More than one question particle'],
  [10, '141A', 'Writing Systems',
    'Alphabetic', 'Consonantal', 'Alphasyllabic', 'Syllabic', 'Logographic', 'Mixed logographic–syllabic'],
  [10, '142A', 'Para-Linguistic Usages of Clicks',
    "Clicks may express logical meanings ('yes' and/or 'no')", 'Clicks may express affective but not logical meanings', 'Clicks may express neither affective nor logical meanings'],
  [5, '143A', 'Order of Negative Morpheme and Verb',
    'NegV', 'VNeg', '[Neg-V]', '[V-Neg]', 'Negative Tone', 'Type 1 / Type 2', 'Type 1 / Type 3', 'Type 1 / Type 4', 'Type 2 / Type 3', 'Type 2 / Type 4', 'Type 3 / Type 4', 'Type 3 / Negative Infix', 'Optional Single Negation', 'Obligatory Double Negation', 'Optional Double Negation', 'Optional Triple Negation with Obligatory Double Negation', 'Optional Triple Negation with Optional Double Negation'],
  [5, '143B', 'Obligatory Double Negation',
    'NegVNeg', 'Neg[V-Neg]', '[Neg-V]Neg', '[Neg-V-Neg]', 'Negative tone & VNeg', 'Negative tone & [Neg-V]', 'NegNegV', 'Neg[Neg-V]', 'VNegNeg', 'Type 1 / Type 2', 'Type 1 / Type 3', 'Type 1 / Type 5', 'Type 1 / Type 7', 'Type 1 / Type 9', 'Type 2 / Type 4', 'Obligatory double negation with optional triple negation'],
  [5, '143C', 'Optional Double Negation',
    'NegV(Neg)', '(Neg)VNeg', 'Neg[V(-Neg)]', '(Neg)[V-Neg]', '[Neg-V](Neg)', '[(Neg-)V]Neg', '[Neg-V(-Neg)]', '[(Neg-)V-Neg]', 'V(Neg)Neg', '[V-Neg](Neg)', 'Neg(Neg)V', 'Neg[(Neg-)]V', 'NegV plus optional change to verb stem', 'NegV/[Neg-V-Neg]', 'VNeg/[Neg-V-Neg]', '[Neg-V]/NegVNeg', 'NegV or NegativeTone&VNeg', 'NegV/[V-Neg]/Neg[V-Neg]', 'NegV/VNeg/NegVNeg', 'NegV/[V-Neg]/[Neg-V-Neg]', '[Neg-V]/VNeg/[Neg-V-Neg]', 'NegV/[Neg-V]/Neg[Neg-V]', 'Optional double negation with optional triple negation'],
  [5, '143D', 'Optional Triple Negation',
    '(Neg)[Neg-V-Neg]', '[V-Neg]Neg with optional negative infix or prefix', 'NegVNeg/NegNegVNeg', '(i) Neg[V-Neg] or (ii) NegVNeg with negative tone', 'Neg[V(-Neg)]Neg/[Neg-V(-Neg)]Neg', 'Neg[V-(Neg)](Neg)'],
  [5, '143E', 'Preverbal Negative Morphemes',
    'Preverbal negative word', 'Negative prefix', 'Both preverbal negative word and negative prefix', 'No preverbal negative morpheme'],
  [5, '143F', 'Postverbal Negative Morphemes',
    'Postverbal negative word', 'Negative suffix', 'Both postverbal negative word and negative suffix', 'No postverbal negative morpheme'],
  [5, '143G', 'Minor morphological means of signaling negation',
    'Negative tone', 'Negative infix', 'Negative stem change', 'No negative tone, infix or stem change'],
  [5, '144A', 'Position of Negative Word With Respect to Subject, Object, and Verb',
    'NegSVO', 'SNegVO', 'SVNegO', 'SVONeg', 'NegSOV', 'SNegOV', 'SONegV', 'SOVNeg', 'NegVSO', 'VSNegO', 'VSONeg', 'NegVOS', 'ONegVS', 'OVNegS', 'OSVNeg', 'More than one position for negative morpheme, with none dominant', 'Optional single negation', 'Obligatory double negation', 'Optional double negation', 'Morphological negation only (but not double negation)', 'Other languages'],
  [5, '144B', 'Position of negative words relative to beginning and end of clause and with respect to adjacency to verb',
    'At beginning of clause separated from verb', 'Preceding verb, separated from verb, but not at beginning of clause', 'Immediately preverbal', 'Immediately postverbal', 'Following verb, separated from verb, but not at end of clause', 'At end of clause, separated from verb'],
  [5, '144C', 'Languages with different word order in negative clauses',
    'VSO, but NegSVO', 'SVO, but SNegOV', 'SVO, but SONegV', 'SVO, but SOVNeg', 'SVO, but NegVSO', 'SVO but SO[V-Neg]', 'SVO but SO[Neg-V]', 'OSV but NegSVO/O[Neg-V]S', 'SVO, but NegSNegOV', 'SVO, but SONeg[V-Neg]/SO[Neg-V-Neg]', 'SOV but  SONeg[V-Neg]/S[Neg-V-Neg] O', 'SVO/VSO, but NegSVONeg', 'SVO/VSO, but [Neg-V]SO(Neg)', 'SVO/SOV, but SVONeg', 'SVO/SOV, but SNegVO', 'SVO/SOV, but SNegOV', 'SVO/SOV, but SOVNeg'],
  [5, '144D', 'The Position of Negative Morphemes in SVO Languages',
    'NegSVO', 'SNegVO', 'SVNegO', 'SVONeg', 'S[Neg-V]O', 'S[V-Neg]O', 'SVO with tonal negation', 'VSO in affirmative clauses, but NegSVO', 'SVO/SOV in affirmative clauses, but SVONeg', 'SVO/SOV in affirmative clauses, but SNegVO', 'Other SVO with preverbal negative word', 'Other SVO with postverbal negative word', 'More than one negative construction', 'SVO with obligatory double negation', 'SVO with optional double negation'],
  [5, '144E', 'Multiple Negative Constructions in SVO Languages',
    'SNegVO/SVNegO', 'NegSVO/SNegVO', 'NegSVO/SVNegO', 'SNegVO/SVONeg', 'SVNegO/SVONeg', 'SVO & Flexible Neg', 'SNegVO/S[V-Neg]O', 'S[Neg-V]O/SVNegO', 'NegSVO/SNegVO/S[V-Neg]O', 'SNegVO/NegVSO', 'SVONeg/VSONeg', 'NegSVO/NegVOS', 'SNegVO/NegVOS', 'S[Neg-V]O/[Neg-V]OS', 'SVONeg/SONegV', 'SVNegO/SOVNeg', 'SVONeg/SNegOV/SOVNeg', 'NegSVO/SVNegO/NegSOV/SNegOV', 'SNegVO/SONegV/SVONeg/SOVNeg', 'S[Neg-V]O/SO[Neg-V]', 'S[V-Neg]O/SO[V-Neg]', 'SNegVO/SONegV/S[Neg-V]O/SO[Neg-V]', 'NegSVO/O[Neg-V]S', 'SVO & NegV/VNeg', 'SVO & NegV/[V-Neg]', 'SVO/VSO & NegV', 'SVO/VOS & NegV', 'SVO/SOV & NegV/VNeg'],
  [5, '144F', 'Obligatory Double Negation in SVO languages',
    'SNegVONeg', 'SNegVNegO', 'SVNegONeg', 'SVO/VSO in affirmative clauses but NegSVONeg', 'S[Neg-V]ONeg', 'SNeg[V-Neg]O', 'S[Neg-V]NegO', 'NegS[V-Neg]O', 'S[Neg-V-Neg]O', 'SVNegO with negative tone on verb', 'S[Neg-V]O with negative tone on verb', 'SNegNegVO/SNegVNegO', 'SNegVNegO/SNegVONeg', 'SNegVONeg/S[Neg-V]ONeg', '(Neg)S(Neg)VONeg (at least one of the preverbal Negs)', 'SNeg[V-Neg]O and negative tone on verb / SNegVNegO', 'S(Neg)[Neg-V-Neg]O', 'SNeg[V(-Neg)]ONeg/S[Neg-V(-Neg)]ONeg', 'SNegVONeg/SNegOVNeg', 'SVONeg with negative tone on verb / SNegOVNeg', 'SNegVONeg/SVNegONeg/NegVOSNeg/VNegOSNeg', 'SVO & NegVNeg', 'S[Neg-V]O & NegV'],
  [5, '144G', 'Optional Double Negation in SVO languages',
    'SNegVO(Neg)', 'S(Neg)VONeg', 'S(Neg)VNegO', 'SNegV(Neg)O', '(Neg)SVONeg', 'SVNegO(Neg)', 'NegS[V(-Neg)]O', 'S[(Neg-)V]NegO', 'S[Neg-V]O(Neg)', 'SNegVO or SVNegO with tone on verb', 'S(Neg)[V(-Neg)]O', 'S[Neg-V(-Neg)]O', '(Neg)SVONeg/S(Neg)VONeg', 'S[Neg-V]O/NegSVNegO', 'SNeg[V-Neg]O/S[Neg-V-Neg]O', 'S[V(-Neg)]O & NegV', 'SVO/SOV & (Neg)[V-Neg]', 'SVO/VSO & NegV/VNeg/NegVNeg'],
  [5, '144H', 'NegSVO Order',
    'Separate word, no double negation', 'Separate word, optional double negation, with NegSVO possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'SVO but NegSVO does not occur'],
  [5, '144I', 'SNegVO Order',
    'Separate word, no double negation', 'Prefix, no double negation', 'Separate word, optional double negation, with SNegVO possible without a second negative', 'Prefix, optional double negation, with SNegVO possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'Prefix, only occurs with another negative morpheme', 'Type 1 / Type 2', 'SVO, but SNegVO does not occur'],
  [5, '144J', 'SVNegO Order',
    'Separate word, no double negation', 'Suffix, no double negation', 'Separate word, optional double negation, with SVNegO possible without a second negative', 'Suffix, optional double negation, with SVNegO possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'Suffix, only occurs with another negative morpheme', 'SVO, but SVNegO does not occur'],
  [5, '144K', 'SVONeg Order',
    'Separate word, no double negation', 'Separate word, optional double negation, with SVONeg possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'SVO but SVONeg does not occur'],
  [5, '144L', 'The Position of Negative Morphemes in SOV Languages',
    'NegSOV', 'SNegOV', 'SONegV', 'SOVNeg', 'SO[Neg-V]', 'SO[V-Neg]', 'SNegOV but SVO in affirmative clauses', 'SONegV but SVO in affirmative clauses', 'SOVNeg but SVO in affirmative clauses', 'SO[V-Neg] but SVO in affirmative clauses', 'SO[Neg-V] but SVO in affirmative clauses', 'SNegOV but SVO/SOV in affirmative clauses', 'SOVNeg but SVO/SOV in affirmative clauses', 'Other SOV with preverbal negative word', 'More than one negative construction', 'SOV with obligatory double negation', 'SOV with optional double negation', 'SV & OV & NegV', 'SV & OV & VNeg', 'SV & OV & negative prefix', 'SV & OV & negative suffix', 'SV & OV with immediately preverbal negative word', 'SV & OV with clause-initial negative word'],
  [5, '144M', 'Multiple Negative Constructions in SOV Languages',
    'SONegV/SOVNeg', 'SNegOV/SONegV', 'NegSOV/SNegOV/SONegV', 'NegSOV or SOV with second position negative word', 'SOVNeg/SO[V-Neg]', 'SO[Neg-V]/SO[V-Neg]', 'SO[Neg-V] or SOV with negative infix', 'SNegOV/SONegV/SO[V-Neg]', 'SONegV/SVONeg', 'SOVNeg/SVNegO', 'SNegOV/SOVNeg/SVONeg', 'NegSOV/SNegOV/NegSVO/SVNegO', 'SONegV/SOVNeg/SNegVO/SVONeg', 'SO[Neg-V]/S[Neg-V]O', 'SO[V-Neg]/S[V-Neg]O/', 'SONegV/SO[Neg-V]/SNegVO/S[Neg-V]O', 'NegSOV/NegOVS', 'SOVNeg/OVNegS', 'SO[V-Neg]/O[V-Neg]S', 'SOV & NegV/VNeg', 'SOV & NegV/[Neg-V]', 'SOV & NegV/[V-Neg]', 'SOV & NegV/VNeg', 'SV & OV & NegV/VNeg', 'SV & OV & NegV/[V-Neg]', 'SV & OV & [Neg-V]/[V-Neg]', 'SV & OV & VNeg/[V-Neg]'],
  [5, '144N', 'Obligatory Double Negation in SOV languages',
    'SONegVNeg', 'NegSNegOV but SVO in affirmative clauses', 'NegSO[V-Neg]', 'SONeg[V-Neg]', 'SO[Neg-V]Neg', 'SO[Neg-V-Neg]', 'SO[Neg-V] with negative tone on verb\tSO[Neg-V]&NegTone', 'SONegVNeg/SONeg[V-Neg]', 'SONeg[V-Neg]/SO[Neg-V-Neg] but SVO in affirmative clauses', 'SNegO[V-Neg]/SONeg[V-Neg]', 'SO[V-Neg]Neg with optional negative prefix or infix', 'SNegOVNeg/SNegVONeg', 'SNegOVNeg or SVONeg with negative tone on verb', 'SOV & NegVNeg', 'SOV & Neg[V-Neg]', 'SOV & Neg[Neg-V]', 'SV & OV & Neg[V-Neg]', 'SV & OV & [Neg-V-Neg]'],
  [5, '144O', 'Optional Double Negation in SOV languages',
    'NegSOV(Neg)', 'S(Neg)OVNeg', 'SNegOV(Neg)', 'SNegO[V(-Neg)]', 'SO[(Neg-)V]Neg', 'SO[Neg-V(-Neg)]', 'SO[(Neg-)V-Neg]', 'SO[V-Neg](Neg)', 'SOVNeg/SO[Neg-V-Neg]', 'SNegO[V(-Neg)](Neg)', 'S[Neg-V-Neg]O/SO[V-Neg] but SOV in affirmative clauses', 'SO[Neg-V-(Neg)]/SOVNeg', '(Neg)SOVNeg/S(Neg)OVNeg/SO(Neg)VNeg', 'S(Neg)O[V(-Neg)]/SO(Neg)[V(-Neg)]', 'SOV & (Neg)[V-Neg]', 'SOV & (Neg)[V(-Neg)]', 'SOV/SVO & Neg[V-(Neg)]', 'SV & OV & (Neg)V(Neg)', 'SV & OV &  (Neg)[V-Neg]', 'SV & OV &  [Neg-V(-Neg)]', 'SV & OV &  [(Neg-)V-Neg]'],
  [5, '144P', 'NegSOV Order',
    'Separate word, no double negation', 'Separate word, optional double negation, with NegSOV possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'SOV but NegSOV does not occur'],
  [5, '144Q', 'SNegOV Order',
    'Separate word, no double negation', 'Separate word, optional double negation, with SNegOV possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'SOV but SNegOV does not occur'],
  [5, '144R', 'SONegV Order',
    'Separate word, no double negation', 'Prefix, no double negation', 'Separate word, optional double negation, with SONegV possible without a second negative', 'Prefix, optional double negation, with SONegV possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'Prefix, only occurs with another negative morpheme', 'Type 1 / Type 2', 'SOV, but SONegV does not occur'],
  [5, '144S', 'SOVNeg Order',
    'Separate word, no double negation', 'Suffix, no double negation', 'Separate word, optional double negation, with SONegV possible without a second negative', 'Suffix, optional double negation, with SONegV possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'Suffix, only occurs with another negative morpheme', 'Type 1 / Type 2', 'Type 1 / Type 6', 'Type 5 / Type 4', 'Type 5 / Type 6', 'SOV, but SOVNeg does not occur'],
  [5, '144T', 'The Position of Negative Morphemes in Verb-Initial Languages',
    'NegVSO', 'VSNegO', 'VSONeg', 'NegVOS', 'NegVSO/NegVOS', 'NegV & VS & VO', 'NegVSO but SVO in affirmative clauses', 'VSO with negative prefix', 'VOS with negative prefix', 'VOS with negative suffix', '[V-Neg] & VS &VO', 'NegVSO/[Neg-V]SO', 'NegVOS/[Neg-V]OS', 'NegVSO/SNegVO', 'VSONeg/SVONeg', 'NegVOS/NegSVO', 'NegVOS/SNegVO', '[Neg-V]OS/S[Neg-V]O', 'NegV & VSO/SVO', 'NegV & VOS/SVO', 'Verb-initial with optional single negation', 'Verb-initial with obligatory double negation', 'Verb-initial with optional double negation'],
  [5, '144U', 'Double negation in verb-initial languages',
    'NegVNegSO', 'NegVNegOS', 'NegVSONeg', 'NegNegVSO', 'VNegSONeg', 'VS & VO & [Neg-V-Neg]', 'NegVOSNeg/VNegOSNeg/SNegVONeg/SVNegONeg', 'V(Neg)SONeg', 'Neg(Neg)VSO', 'NegVSO/[Neg-V-Neg]SO', 'NegVSO with optional stem change', '[Neg-V]SO(Neg) but SVO/VSO in affirmative clauses', 'VS & VO & Neg[(Neg-)V]', 'VS & VO & NegV/[(Neg-)V-Neg]', 'VOS & NegVNeg', 'VSO/SVO & (Neg)V(Neg)'],
  [5, '144V', 'Verb-Initial with Preverbal Negative',
    'Separate word, no double negation\tWord&NoDoubleNeg', 'Prefix, no double negation\tPrefix&NoDoubleNeg', 'Separate word, optional single or double negation, with preverbal negative word possible without a second negative', 'Prefix, optional double negation, with negative prefix possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'Prefix, only occurs with another negative morpheme', 'Type 1 / Type 2', 'Type 3 / Type 6', 'Verb-initial but preverbal negative does not occur'],
  [5, '144W', 'Verb-Initial with Negative that is Immediately Postverbal or between Subject and Object',
    'Suffix, no double negation', 'Separate word, immediately following verb, only occurs with another negative morpheme', 'Suffix, optional double negation, can occur without a second negative', 'Suffix, only occurs with another negative morpheme', 'Separate word, between subject and object', 'Verb-initial but immediately postverbal negative or negative between subject and object does not occur'],
  [5, '144X', 'Verb-Initial with Clause-Final Negative',
    'Separate word, no double negation', 'Separate word, optional double negation, with clause-final negative word possible without a second negative', 'Separate word, only occurs with another negative morpheme', 'Verb-initial but clause-final negative does not occur'],
  [5, '144Y', 'The Position of Negative Morphemes in Object-Initial Languages',
    'ONegVS', 'OVNegS', 'OSVNeg', 'O[V-Neg]S', 'OS(Neg)[V(-Neg)]', 'O[Neg-V-Neg]S', 'OVNegS/SOVNeg', 'NegOVS/NegSOV', 'O[V-Neg]S/SO[V-Neg]', 'O[Neg-V]S/NegSVO', 'OVS & NegV']
]
if __name__ == '__main__':
    features.sort(key=lambda x: x[0])
    f = open('walsform.html', 'w')
    f.write('<form id="submit" method="post" action="submitwals.php/">')
    f.write('<input type="text" id="id" name="id" style="display: none;"></input>')
    f.write('<table border="1"><tbody>')
    x = -1
    for fl in features:
        if fl[0] != x:
            f.write('<tr><td colspan="2"><h2>%s</h2></td></tr>' % areas[fl[0]])
            x += 1
        f.write('<tr><td><a href="http://wals.info/feature/%s">%s</a></td><td><select name="%s" id="%s">' % (fl[1], fl[2], fl[1], fl[1]))
        f.write('<option value="0">----</option>')
        for i in range(3, len(fl)):
            f.write('<option value="%s">%s</option>' % (i-2, fl[i]))
        f.write('</select></td></tr>')
    f.write('</tbody></table>')
    f.write('<input type="submit"></input>')
    f.write('</form>')
    f.close()
